- name: "approved"
  description: "Pull Request has been approved and can be merged"
  color: "0E8A16"
- name: "automation"
  description: "Changes to the repository automation"
  color: "ededed"
- name: "blocked"
  description: "Need more information"
  color: "212121"
- name: "bot"
  description: "Action was performed by a bot"
  color: "ededed"
- name: "bug"
  description: "Something isn't working"
  color: "ee0701"
- name: "changes-requested"
  description: "Pull Request needs changes before it can be reviewed again"
  color: "AA2626"
- name: "critical"
  description: "Urgent!"
  color: "EE0701"
- name: "DANGERZONE"
  description: "Poor implementation can introduce security issues. Extra care needs to be taken."
  color: "b60205"
- name: "dependencies"
  description: "Pull requests that update a dependency file"
  color: "0366d6"
- name: "documentation"
  description: "Improvements or additions to documentation"
  color: "ededed"
- name: "duplicate"
  description: "This issue or pull request already exists"
  color: "eeeeee"
- name: "enhancement"
  description: "Improvements to existing features"
  color: "6842a5"
- name: "fixed"
  description: "Bug has been fixed"
  color: "ededed"
- name: "good-first-issue"
  description: "Good issue for new developers to start with"
  color: "0052cc"
- name: "has-conflicts"
  description: "PR has merge conflicts that need to be resolved"
  color: "000000"
- name: "help-wanted"
  description: "Looking for someone to assist with this"
  color: "d021a9"
- name: "high"
  description: "High priority"
  color: "74d600"
- name: "in-progress"
  description: "Actively being worked on"
  color: "87f776"
- name: "implemented"
  description: "Feature or enhanement has been implemented"
  color: "ededed"
- name: "invalid"
  description: "This doesn't seem right"
  color: "eeeeee"
- name: "low"
  description: "Low priority"
  color: "6495ED"
- name: "merge-ready"
  description: "The PR is ready to merge!"
  color: "FF00FF"
- name: "merged"
  description: "The PR has been merged"
  color: "6F42C1"
- name: "needs-triage"
  description: "Someone needs to choose a priority"
  color: "e3e4e6"
- name: "needs-discussion"
  description: "A conversation is needed to iron out some details"
  color: "eeeeee"
- name: "needs-more-approvals"
  description: "The PR needs more approvals"
  color: "96C823"
- name: "new-feature"
  description: "New feature or request"
  color: "f8f8fa"
- name: "on-hold"
  description: "On hold, do not work on this"
  color: "cccccc"
- name: "pending-pr"
  description: "There is a PR associated with this issue"
  color: 8311fc
- name: "question"
  description: "Further information is required"
  color: "5319e7"
- name: "ready-for-review"
  description: "PR is waiting for reviews"
  color: "334796"
- name: "ready-for-testing"
  description: "Ready for QA"
  color: "22ed1e"
- name: "SECURITY-IMPACT"
  description: "There could be security impacts. Pay extra attention to this."
  color: "b60205"
- name: "ui-ux"
  description: "User interface and user experience"
  color: "500bb7"
- name: "WIP"
  description: "Work in progress. Please do not review or merge."
  color: "FBCA04"
- name: "wontfix"
  description: "This will not be worked on"
  color: "000000"
# Size labels. Works with size label in the auto_label workflow
- name: "size/XS"
  description: "Extra small PR. Very quick to review"
  color: "037350"
- name: "size/S"
  description: "Small PR. Quick to review"
  color: "5e60ba"
- name: "size/M"
  description: "Average size PR."
  color: "0D12E8"
- name: "size/L"
  description: "Big PR. Extra attention required"
  color: "bc00ac"
- name: "size/XL"
  description: "Huge PR. May require additional reviewers"
  color: "C32607"
- name: "size/XXL"
  description: "Massive PR. Please consider refactoring into smaller features"
  color: "E50009"
# Filetype Labels. Works with the file_labels.yml and auto_label workflow
- name: "javascript"
  description: "JS files have been changed or added"
  color: "ededed"
- name: "html"
  description: "HTML files have been changed or added"
  color: "ededed"
- name: "styles"
  description: "Style changes have been introduced"
  color: "ededed"
- name: "vue"
  description: "Vue files have been changed or added"
  color: "ededed"
- name: "unit-tests"
  description: "Unit tests have been added or updated"
  color: "ededed"
- name: "integration-tests"
  description: "Integration tests have been added or updated"
  color: "ededed"
- name: "database"
  description: "Database files have been changed"
  color: "ededed"
- name: "migrations"
  description: "Database migrations have been updated"
  color: "ededed"
- name: "seed-data"
  description: "Database seeding changes have been introduced"
  color: "ededed"
- name: "json"
  description: "JSON files have been changed or added"
  color: "ededed"
- name: "xml"
  description: "XML files have been changed or added"
  color: "ededed"
- name: "scripts"
  description: "Shell scripts have been changed or added"
  color: "ededed"
- name: "images"
  description: "Images have been added or updated"
  color: "ededed"
- name: "webpack-config"
  description: "Webpack config has changed"
  color: "ededed"
- name: "webpack-config"
  description: "Automation has been updated"
  color: "ededed"
- name: "fonts"
  description: "Fonts have been added or changed"
  color: "ededed"
- name: "configuration"
  description: "Configuration has changed"
  color: "ededed"
- name: "examples"
  description: "Example files have been updated"
  color: "ededed"
- name: "jsx"
  description: "JSX files have been added or changed"
  color: "ededed"
- name: "php"
  description: "PHP files have been changed or added"
  color: "ededed"
- name: "templates"
  description: "Template or layout files have been changed or added"
  color: "ededed"
- name: "stuck"
  description: "The PR build appears to be stuck"
  color: "f12222"
