# GitHub Workflow (c) Unicorn Global
name: Audit Secrets
on:
  pull_request:
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Check for secrets
      uses: UnicornGlobal/trufflehog-actions-scan@master
      with:
        branch: ${{ github.head_ref }}
