name: PR Labels
on:
  pull_request:

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/file_labels.yml'
  sizes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: UnicornGlobal/pr-size-labels@master
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  conditions:
    runs-on: ubuntu-latest
    steps:
    - uses: srvaroa/labeler@master
      with:
        config_path: '.github/auto_labels.yml'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  conflicts:
    runs-on: ubuntu-latest
    steps:
    - uses: mschilde/auto-label-merge-conflicts@master
      with:
        CONFLICT_LABEL_NAME: "has-conflicts"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
