# GitHub Workflow (c) Unicorn Global
name: Validate Markdown
on:
  pull_request:
    paths:
      - '**.md'
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
