name: Sync

on:
  pull_request:
    types:
    - opened

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync Labels
      uses: crazy-max/ghaction-github-labeler@v2.0.2
      with:
        yaml_file: .github/github_label_setup.yml
        exclude: "['help*', '*issue']"
        skip_delete: false
        dry_run: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
